name: Start Splunk Server

on: [push, pull_request]

jobs:
  splunk-action:
    name: Start Splunk Server

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start Splunk Server
        uses: ./
        with:
          splunk-image: "splunk/splunk:latest"
          splunk-container-name: ${{ vars.SPLUNK_CONTAINER_NAME }}
          splunk-apps-url: ${{ vars.SPLUNK_APPS_URL }}
          splunk-password: ${{ secrets.SPLUNK_PASSWORD }}
          splunk-cloud-username: ${{ vars.SPLUNK_CLOUD_USERNAME }}
          splunk-cloud-password: ${{ secrets.SPLUNK_CLOUD_PASSWORD }}
          splunk-license-uri: ${{ vars.SPLUNK_LICENSE_URI }}
          splunk-app-port: "8000"
          splunk-mgmt-port: "8089"
          timezone: "UTC"
