name: Start Splunk Server

on: [push, pull_request]

jobs:
  splunk-action:
    name: Start Splunk Server

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start Splunk Server
        uses: ./
        with:
          splunk-image: "splunk/splunk:latest"
          splunk-apps-url: ${SPLUNK_APPS_URL}
          splunk-password: ${SPLUNK_PASSWORD}
          splunk-cloud-username: ${SPLUNK_CLOUD_USERNAME}
          splunk-cloud-password: ${SPLUNK_CLOUD_PASSWORD}
          splunk-license-uri: ${SPLUNK_LICENSE_URI}
          splunk-app-port: "8000"
          splunk-mgmt-port: "8089"
          timezone: "UTC"
